version: '3.8'
services:
    worker:
        build:
            context: ../
            args:
                - APP_PORT=${APP_PORT}
        ports:
            - "${APP_PORT}:${APP_PORT}"
        volumes:
            - ..:/worker
            - ../node_modules:/app/node_modules
        env_file:
            - .env
